"""AgentEnv + ChannelInfo — unified per-message agent environment.

Generated on each incoming message, providing a single source of truth
for channel capabilities, agent identity, credentials, and workgroup state.
"""

from dataclasses import dataclass, field


@dataclass(frozen=True)
class ChannelInfo:
    """Where this message came from.

    Generated by the channel handler (Telegram / Web) and attached to
    IncomingMessage. Downstream code queries properties instead of
    checking ``msg.channel == "..."`` everywhere.
    """

    platform: str  # "telegram" / "web"

    # ── Telegram ──
    telegram_chat_type: str = ""  # "private" / "group" / "supergroup" / "channel"

    # ── Derived capabilities ──

    @property
    def is_dm(self) -> bool:
        if self.platform == "telegram":
            return self.telegram_chat_type == "private"
        return False

    @property
    def is_thread(self) -> bool:
        return False

    @property
    def is_group(self) -> bool:
        if self.platform == "telegram":
            return self.telegram_chat_type in ("group", "supergroup")
        return False

    @property
    def supports_webhooks(self) -> bool:
        return False

    @property
    def supports_topic(self) -> bool:
        return False

    @property
    def supports_threads(self) -> bool:
        return False

    @property
    def supports_inline_keyboard(self) -> bool:
        return False

    @property
    def supports_media_upload(self) -> bool:
        """Telegram supports photo/file/video via MCP."""
        return self.platform == "telegram"

    @property
    def reply_channel_id(self) -> str:
        """The channel ID to send replies to."""
        return ""


# Convenience constructors

def telegram_private() -> ChannelInfo:
    return ChannelInfo(platform="telegram", telegram_chat_type="private")


def telegram_group(chat_type: str = "supergroup") -> ChannelInfo:
    return ChannelInfo(platform="telegram", telegram_chat_type=chat_type)


def web_channel() -> ChannelInfo:
    return ChannelInfo(platform="web")


@dataclass(frozen=True)
class AgentEnv:
    """Per-message agent environment.

    Generated by Router on each incoming message from the current state
    of the bot, pool, and workgroup.  Passed through the entire dispatch
    chain: Router → Process → Callback → Context injection.
    """

    # ── Message context ──
    channel: ChannelInfo = field(default_factory=lambda: ChannelInfo(platform="unknown"))
    chat_id: str = ""
    user_id: str = ""
    via_workgroup: bool = False

    # ── Agent identity ──
    bot_name: str = ""
    display_name: str = ""
    node_id: str = ""
    workspace: str = ""
    config_dir: str = ""
    local_dir: str = ""

    # ── Credentials ──
    telegram_token: str = ""  # non-empty = can use telegram MCP
    has_peer_channel: bool = False  # True = can use peer MCP

    # ── Workgroup ──
    workgroup_role: str = ""  # "" / "admin" / "specialist"
    workgroup_agents: tuple[str, ...] = ()
    running_tasks: tuple = ()
    peers: tuple = ()  # workgroup admins this admin can send_to_peer (cluster registry)

    # ── Config ──
    ai_backend: str = "claude-cli"
    model: str = ""
    yolo: bool = False
    passthrough: bool = False  # raw bot: skip context + MCP injection

    # ── Derived ──

    @property
    def is_workgroup_admin(self) -> bool:
        return self.workgroup_role == "admin"

    @property
    def is_specialist(self) -> bool:
        return self.workgroup_role == "specialist"

    @property
    def has_telegram(self) -> bool:
        return bool(self.telegram_token)

    def callback_webhook_name(self) -> str:
        """Webhook identity for replies. Empty = send as bot itself."""
        return ""

    def heartbeat_display_mode(self) -> str:
        """How heartbeat should display: 'text' / 'none'."""
        if self.channel.is_dm:
            return "text"
        return "none"
