"""AgentEnv + ChannelInfo — unified per-message agent environment.

Generated on each incoming message, providing a single source of truth
for channel capabilities, agent identity, credentials, and workgroup state.
"""

from dataclasses import dataclass, field


@dataclass(frozen=True)
class ChannelInfo:
    """Where this message came from.

    Generated by the channel handler (Discord/Telegram) and attached to
    IncomingMessage.  Downstream code queries properties instead of
    checking ``msg.channel == "discord"`` everywhere.
    """

    platform: str  # "telegram" / "discord" / "web"

    # ── Discord ──
    discord_channel_type: str = ""  # "guild_text" / "guild_thread" / "dm" / ""
    discord_guild_id: int = 0
    discord_category_id: int = 0
    discord_channel_id: int = 0
    discord_thread_id: int = 0

    # ── Telegram ──
    telegram_chat_type: str = ""  # "private" / "group" / "supergroup" / "channel"

    # ── Derived capabilities ──

    @property
    def is_dm(self) -> bool:
        if self.platform == "discord":
            return self.discord_channel_type == "dm"
        if self.platform == "telegram":
            return self.telegram_chat_type == "private"
        return False

    @property
    def is_thread(self) -> bool:
        return self.discord_channel_type == "guild_thread"

    @property
    def is_group(self) -> bool:
        if self.platform == "telegram":
            return self.telegram_chat_type in ("group", "supergroup")
        return False

    @property
    def supports_webhooks(self) -> bool:
        """Discord guild text channels support webhooks; DM/threads don't."""
        return self.platform == "discord" and self.discord_channel_type == "guild_text"

    @property
    def supports_topic(self) -> bool:
        return self.platform == "discord" and self.discord_channel_type == "guild_text"

    @property
    def supports_threads(self) -> bool:
        return self.platform == "discord" and self.discord_channel_type == "guild_text"

    @property
    def supports_inline_keyboard(self) -> bool:
        return self.platform == "discord"

    @property
    def supports_media_upload(self) -> bool:
        """Telegram supports photo/file/video via MCP."""
        return self.platform == "telegram"

    @property
    def reply_channel_id(self) -> str:
        """The channel ID to send replies to."""
        if self.discord_thread_id:
            return str(self.discord_thread_id)
        if self.discord_channel_id:
            return str(self.discord_channel_id)
        return ""


# Convenience constructors

def discord_guild_channel(
    guild_id: int, category_id: int, channel_id: int,
) -> ChannelInfo:
    return ChannelInfo(
        platform="discord",
        discord_channel_type="guild_text",
        discord_guild_id=guild_id,
        discord_category_id=category_id,
        discord_channel_id=channel_id,
    )


def discord_thread(
    guild_id: int, category_id: int, parent_channel_id: int, thread_id: int,
) -> ChannelInfo:
    return ChannelInfo(
        platform="discord",
        discord_channel_type="guild_thread",
        discord_guild_id=guild_id,
        discord_category_id=category_id,
        discord_channel_id=parent_channel_id,
        discord_thread_id=thread_id,
    )


def discord_dm(channel_id: int) -> ChannelInfo:
    return ChannelInfo(
        platform="discord",
        discord_channel_type="dm",
        discord_channel_id=channel_id,
    )


def telegram_private() -> ChannelInfo:
    return ChannelInfo(platform="telegram", telegram_chat_type="private")


def telegram_group(chat_type: str = "supergroup") -> ChannelInfo:
    return ChannelInfo(platform="telegram", telegram_chat_type=chat_type)


def web_channel() -> ChannelInfo:
    return ChannelInfo(platform="web")


@dataclass(frozen=True)
class AgentEnv:
    """Per-message agent environment.

    Generated by Router on each incoming message from the current state
    of the bot, pool, and workgroup.  Passed through the entire dispatch
    chain: Router → Process → Callback → Context injection.
    """

    # ── Message context ──
    channel: ChannelInfo = field(default_factory=lambda: ChannelInfo(platform="unknown"))
    chat_id: str = ""
    user_id: str = ""
    via_workgroup: bool = False

    # ── Agent identity ──
    bot_name: str = ""
    display_name: str = ""
    node_id: str = ""
    workspace: str = ""
    config_dir: str = ""
    local_dir: str = ""

    # ── Credentials ──
    telegram_token: str = ""  # non-empty = can use telegram MCP
    has_peer_channel: bool = False  # True = can use peer MCP

    # ── Workgroup ──
    workgroup_role: str = ""  # "" / "admin" / "specialist"
    workgroup_agents: tuple[str, ...] = ()
    running_tasks: tuple = ()

    # ── Config ──
    ai_backend: str = "claude-cli"
    model: str = ""
    yolo: bool = False

    # ── Derived ──

    @property
    def is_workgroup_admin(self) -> bool:
        return self.workgroup_role == "admin"

    @property
    def is_specialist(self) -> bool:
        return self.workgroup_role == "specialist"

    @property
    def has_telegram(self) -> bool:
        return bool(self.telegram_token)

    def mcp_server_names(self) -> list[str]:
        """Which MCP servers to inject for this turn."""
        servers = ["boxagent"]
        if self.is_workgroup_admin:
            servers.append("boxagent-admin")
        if self.has_telegram:
            servers.append("boxagent-telegram")
        if self.has_peer_channel:
            servers.append("boxagent-peer")
        return servers

    def callback_webhook_name(self) -> str:
        """Webhook identity for replies. Empty = send as bot itself."""
        if self.via_workgroup and self.channel.supports_webhooks:
            return self.bot_name
        return ""

    def heartbeat_display_mode(self) -> str:
        """How heartbeat should display: 'webhook' / 'text' / 'none'."""
        if self.channel.supports_webhooks:
            return "webhook"
        if self.channel.is_dm:
            return "text"
        return "none"
